name: booking-order-app
services:
    user-service:
        container_name: user-service
        image: andreasuryatanaya/user-service:13
        ports:
            - "8001:8001"
        env_file:
            - .env
